### ISSUE TITLE
Invalid plugins configuration with transform-regenerator and arrow functions

### ISSUE THREAD

**Issue by Strate** [babel/babel-preset-env#160]
With config such as:
```
                ["env", {
                    "targets": {
                        "chrome": 55,
                        "firefox": 51,
                        "node": "current"
                    },
                    "modules": false,
                    "useBuiltIns": true,
                    "debug": false,
                }]
```
I got error when use async arrow function from "transform-regenerator" plugin:
```
/devel/src/front/src/lib/entities/store/ApiStore.ts: unknown Expression of type "ArrowFunctionExpression"
    at /devel/src/front/node_modules/regenerator-transform/lib/emit.js:1035:15
    at Emitter.Ep.explodeExpression (/devel/src/front/node_modules/regenerator-transform/lib/emit.js:1037:4)
    at explodeViaTempVar (/devel/src/front/node_modules/regenerator-transform/lib/emit.js:810:23)
    at /devel/src/front/node_modules/regenerator-transform/lib/emit.js:893:24
    at Array.forEach (native)
    at /devel/src/front/node_modules/regenerator-transform/lib/emit.js:892:18
    at Emitter.Ep.explodeExpression (/devel/src/front/node_modules/regenerator-transform/lib/emit.js:1037:4)
    at /devel/src/front/node_modules/regenerator-transform/lib/emit.js:840:45
    at Emitter.Ep.explodeExpression (/devel/src/front/node_modules/regenerator-transform/lib/emit.js:1037:4)
    at /devel/src/front/node_modules/regenerator-transform/lib/emit.js:874:30 _babel: true }
 60% building modules 936/1115 modules 179 active ...an/front/src/lib/utils/assertNever.ts
```

**Comment by SerkanSipahi** [comment]
@Strate please share your code

**Comment by Strate** [comment]
@SerkanSipahi https://github.com/Strate/babel-preset-env-issue-160

**Comment by yavorsky** [comment]
@Strate This issue is caused by regenerator-transform, so I [created PR](https://github.com/facebook/regenerator/pull/277) and if it's ok - the problem will be solved.

**Comment by yavorsky** [comment]
@Strate BTW, You can [include](https://github.com/babel/babel-preset-env#include) `babel-plugin-transform-es2015-arrow-functions` to fix this for now.

**Comment by damianobarbati** [comment]
+1 same problem because of firefox here
