### ISSUE TITLE
TypeError: Cannot read property 'loose' of undefined

### ISSUE THREAD

**Issue by tinovyatkin** [babel/babel-preset-env#21]
Error while using example from documentation.

CLI, `babel-node`, 6.16, `babel-preset-env` - `0.0.4`, `.babelrc` content:

```json
{
  "presets": [
    "env", {
      "targets": {
        "node": 6.7
      },
      "modules": false
    }
  ]
}
```

Running command `babel-node tasks/dev` fails with error:

```
/Users/tino/Sites/transfers.do/node_modules/babel-core/lib/transformation/file/options/option-manager.js:333
        throw e;
        ^

TypeError: Cannot read property 'loose' of undefined (While processing preset: "/Users/tino/Sites/transfers.do/node_modules/babel-preset-env/lib/index.js")
    at buildPreset (/Users/tino/Sites/transfers.do/node_modules/babel-preset-env/lib/index.js:93:39)
    at /Users/tino/Sites/transfers.do/node_modules/babel-core/lib/transformation/file/options/option-manager.js:322:46
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/tino/Sites/transfers.do/node_modules/babel-core/lib/transformation/file/options/option-manager.js:269:20)
    at OptionManager.mergePresets (/Users/tino/Sites/transfers.do/node_modules/babel-core/lib/transformation/file/options/option-manager.js:258:10)
    at OptionManager.mergeOptions (/Users/tino/Sites/transfers.do/node_modules/babel-core/lib/transformation/file/options/option-manager.js:243:14)
    at OptionManager.init (/Users/tino/Sites/transfers.do/node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
    at compile (/Users/tino/Sites/transfers.do/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/tino/Sites/transfers.do/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tino/Sites/transfers.do/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by VitorLuizC** [comment]
It is happening to me, right now using `transform-optional-chaining` plugin.

```
Module build failed: TypeError: Cannot read property 'loose' of undefined
    at _default (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-plugin-transform-opti
onal-chaining/lib/index.js:12:31)
    at Function.memoisePluginContainer (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babe
l-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-core/
lib/transformation/file/options/option-manager.js:146:32)
    at /Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-core/lib/transformation/file/op
tions/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-core
/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-cor
e/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-core/lib/tr
ansformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/vitorcavalcanti/Projects/responsive-client/node_modules/babel-loader/lib/index.js:175:20)
```

**Comment by hzoo** [comment]
You must be using babel v6, optional chaining is part of v7
