### ISSUE TITLE
v1.3.0 causes build errors

### ISSUE THREAD

**Issue by echenley** [babel/babel-preset-env#235]
![screen shot 2017-03-30 at 3 57 29 pm](https://cloud.githubusercontent.com/assets/6344219/24525884/b0285a40-1561-11e7-840e-50505b26a787.png)

.babelrc:

```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["last 3 versions"],
        "uglify": true,
      },
    }],
    "react",
    "stage-1"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "transform-flow-strip-types"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        "flow-react-proptypes"
      ]
    },
  }
}
```

Babel Version: 6.23.0
Webpack Version: 2.3.2

---

Temp fix: pin to `babel-preset-env@1.2.2`

**Comment by philwhln** [comment]
I'm hitting this without webpack...

```
> babel src --out-dir build/ --ignore __tests_
Error: Cannot find module '../data/plugin-features' (While processing preset: "/Users/phil/src/otono/redux-utils/node_modules/babel-preset-env/lib/index.js")
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/phil/src/otono/redux-utils/node_modules/babel-preset-env/lib/normalize-options.js:21:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

My `.babelrc`

```
{
  "presets": [
    [
      "env", { "es2015": { "modules": false } }
    ]
  ],
  "plugins": [
    "transform-es2015-modules-commonjs",
    "transform-object-rest-spread"
  ]
}
```

**Comment by hzoo** [comment]
Thanks for reporting, looks like https://github.com/babel/babel-preset-env/pull/216 npmignored too many files

**Comment by existentialism** [comment]
Our bad... v1.3.1 published!

**Comment by jcreamer898** [comment]
Thanks for the quick fix.

**Comment by philwhln** [comment]
Can confirm 1.3.1 is working no our builds! 👍

**Comment by echenley** [comment]
Thank you! Confirmed 1.3.1 fixes the issue. Closing.

**Comment by hzoo** [comment]
Why all packages need a smoke test for if you ignore too many files 😄

**Comment by hzoo** [comment]
@citycide https://github.com/babel/babel-preset-env/issues/238, looks like the published version is different from src for some reason (probably built the wrong branch)

**Comment by citycide** [comment]
Yep I think code from #231 leaked into the releases and came without adding `semver` to dependencies.

**Comment by hzoo** [comment]
`"prepublish": "npm run build"` should solve in the future
