### ISSUE TITLE
targets.uglify in Webpack 2 productionized build

### ISSUE THREAD

**Issue by yingw787** [babel/babel-preset-env#251]
I'm having some difficulty with a bug when building out my project with webpack -p. It's related to the UglifyJS unable to parse ES6, and babel-preset-env apparently not transpiling everything to ES5. Does anybody have any suggestions?

Here's the npm debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle blog.yingw787.com@1.0.0~prebuild: blog.yingw787.com@1.0.0
6 silly lifecycle blog.yingw787.com@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle blog.yingw787.com@1.0.0~build: blog.yingw787.com@1.0.0
8 verbose lifecycle blog.yingw787.com@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle blog.yingw787.com@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/yingwang/javascript_projects/blog.yingw787.com/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go/libexec/bin:/Users/yingwang/.go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/yingwang/.yarn/bin
10 verbose lifecycle blog.yingw787.com@1.0.0~build: CWD: /Users/yingwang/javascript_projects/blog.yingw787.com
11 silly lifecycle blog.yingw787.com@1.0.0~build: Args: [ '-c', 'NODE_ENV=\'production\' npm run clean && webpack -p' ]
12 silly lifecycle blog.yingw787.com@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle blog.yingw787.com@1.0.0~build: Failed to exec build script
14 verbose stack Error: blog.yingw787.com@1.0.0 build: `NODE_ENV='production' npm run clean && webpack -p`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid blog.yingw787.com@1.0.0
16 verbose cwd /Users/yingwang/javascript_projects/blog.yingw787.com
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error blog.yingw787.com@1.0.0 build: `NODE_ENV='production' npm run clean && webpack -p`
23 error Exit status 2
24 error Failed at the blog.yingw787.com@1.0.0 build script 'NODE_ENV='production' npm run clean && webpack -p'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the blog.yingw787.com package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     NODE_ENV='production' npm run clean && webpack -p
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs blog.yingw787.com
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls blog.yingw787.com
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

Here's the Webpack config (didn't make a separate .babelrc because I figured it could be inlined in webpack)

```
var webpack = require('webpack');
var path = require('path');

var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: [
        'es6-shim',
        'babel-polyfill',
        './src/index.js'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    resolve: {
        extensions: ['.js', '.jsx'],
        alias: {
            'posts': path.resolve('./posts'),
            'config': path.resolve('./config')
        }
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                loader: 'babel-loader',
                exclude: path.resolve('node_modules'),
                options: {
                    presets: [
                        'react',
                        ['env', {
                            'targets': {
                                'uglify': true
                            }
                        }],
                        'stage-0']
                }
            },
            {
                test: /\.(css)$/,
                use: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            // modules: true, // causes conflict with global namespaced css frameworks.
                            localIndentName: '[name]__[local]__[hash:base64:5]'
                        }
                    }
                ]
            },
            {
                test: /\.(woff|woff2|eot|svg|ttf)$/,
                loader: 'file-loader',
            },
            {
                test: /\.(ico)$/,
                loader: 'file-loader',
                options: {
                    name: '[name].[ext]'
                }
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            favicon: 'src/favicon.ico'
        })
    ]
}
```

I can provide more information on request, planning on open sourcing this project anyways.

**Comment by yingw787** [comment]
Closing issue as the problem is resolved. I had includeded `markdown-it-katex` and `markdown-it-mermaid` into my project, which likely have fat arrow functions, and because I set in my webpack config to ignore all node_modules, the fat arrow functions were being imported directly into my bundle.js.

**Comment by alexsasharegan** [comment]
This was the light bulb I need for my own case!
