### ISSUE TITLE
Options {"modules":false} passed to  babel-preset-env/lib/index.js which does not accept options.

### ISSUE THREAD

**Issue by ruofeng086** [babel/babel-preset-env#339]
`/usr/local/bin/babel src/router/index.js --out-dir dist --source-maps --presets env
Error: Options {"modules":false} passed to /babel-preset-env/lib/index.js which does not accept options.
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328:15
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:378:12)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:52:22)

Process finished with exit code 1`

When I was in webstorm write JavaScript, there will be this error.
How should i solve?

**Comment by yavorsky** [comment]
@ruofeng086 Thanks for the issue. What version of Babel are you using. Would be great if you'll provide a small repo where this issue could be reproduced.

Also some refs:
https://github.com/babel/babel-preset-env/issues/10
https://github.com/babel/babel-preset-env/issues/333
https://github.com/babel/babel-preset-env/issues/331

**Comment by ruofeng086** [comment]
"babel-preset-env": "^1.3.2"

**Comment by ruofeng086** [comment]
`{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
`

this is a config file. use vue-cli generate file.

**Comment by existentialism** [comment]
@ruofeng086 any more details or steps to repro? I used vue-cli to scaffold a new app (via webpack template) and the app booted up just fine :(

**Comment by ruofeng086** [comment]
ide use is webstorm? i use atom without this error.

**Comment by sanperrier** [comment]
just update your `babel-core` package

**Comment by Sventour** [comment]
I'm having the same issue as well, here's the error I'm getting:


>Error: Options {"loose":true} passed to /xxx/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/xx/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/xx/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/xx/node_modules/babel-preset-es2015/lib/index.js")

versions:
"babel-preset-env": "^1.6.0",
"babel-core": "^6.25.0"
"babel-preset-es2015": "^6.24.1"
"babel-preset-react": "^6.24.1"

**Comment by hzoo** [comment]
I think we need a repro to get the error because this works fine for me locally from scratch, also no one is pasting their config? You don't need both env and es2015 either

**Comment by chadfurman** [comment]
Hi, I'm getting this error, also.  I will paste both my error and my config.  Here is my error:

```
ERROR in ./server/index.js
Module build failed: Error: Options {"targets":{"ie":9,"uglify":true},"useBuiltIns":false,"modules":false} passed to /opt/frontend/node_modules/babel-preset-env/lib/index.js which does not accept options.
    at /opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:333:15
    at Array.map (native)
    at OptionManager.resolvePresets (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at /opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:14
    at /opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:342:20
    at Array.map (native)
    at OptionManager.resolvePresets (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/opt/frontend/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/opt/frontend/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/opt/frontend/node_modules/babel-loader/lib/index.js:175:20)
```

Here is my config:

```
      {
        test: /\.jsx?$/,
        use: [{
          loader: 'babel-loader',
          options: {
            ignore: /(node_modules)/,
            presets: ['react', 'es2015'],
            plugins: 'relay'
          }
        }]
      },
```

**Comment by pshort** [comment]
Me too

> Error: Options {"targets":{"node":"current"}} passed to node_modules\babel-preset-env\lib\index.js which does not accept options. (While processing preset: "node_modules\\babel-preset-env\\lib\\index.js") (While processing preset: "node_modules\\babel-preset-env\\lib\\index.js")
>     at node_modules\babel-core\lib\transformation\file\options\option-manager.js:314:17
>     at Array.map (native)
>     at OptionManager.resolvePresets (node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
>     at OptionManager.mergePresets (node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
>     at OptionManager.mergeOptions (node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
>     at OptionManager.init (node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
>     at compile (node_modules\babel-register\lib\node.js:103:45)
>     at loader (node_modules\babel-register\lib\node.js:144:14)
>     at Object.require.extensions.(anonymous function) [as .js] (node_modules\babel-register\lib\node.js:154:7)
>     at Module.load (module.js:488:32)

**Comment by loganfsmyth** [comment]
@pshort Make sure you're not passing `ignore: false` to `babel-register`. See https://github.com/babel/babel/issues/6130#issuecomment-324495961
