### ISSUE TITLE
"Invalid options type for foreign"

### ISSUE THREAD

**Issue by vihanb** [babel/babel-preset-env#351]
This is one of the most unusual bugs I have encountered and I'm not sure if it's with this or babel. I have this in my `.babelrc`:

```
    "presets": [
        ["env", {
            "targets": {
                "node": "4.8"
            }
        }]
    ]
```

and if I compile my `src` directory with `babel src/ -d lib/` everything is fine but when I do `babel src/file.js -p lib/file.js` I get this error:

```
TypeError: [BABEL] src/file.js: Invalid options type for foreign
    at Logger.error (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:267:16)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:14
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:399:22
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:388:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:371:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:331:14)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:437:16)
```

It looks like babel is generating this for the options:

```
{ options: [ 'env', { targets: [Object] } ],
  alias: undefined,
  loc: undefined,
  dirname: '.' }
```

and because `alias` is undefined the error is getting thrown but I have no clue why or what is causing this. All other presets work fine. I am using npm@5, node v7.1.0, and `babel-preset-env` version 1.5.2

**Comment by existentialism** [comment]
@vihanb strange indeed! any chance you can put up a small repo demonstrating the error?

**Comment by vihanb** [comment]
It must have been some issue with a slightly out-of-date version of babel as `npm install`ing again seems to fix the issue.

**Comment by mattdsteele** [comment]
I ran into this issue too. I was able to resolve it by installing `babel-cli@latest` (previously I just had `babel-core`).

**Comment by vijaysutrave** [comment]
Yes, updating `babel-core` to the latest fixes this issue.
