### ISSUE TITLE
Invalid chars at top of bundle

### ISSUE THREAD

**Issue by binarykitchen** [babel/babel-preset-env#371]
Why is, in my case,`babel-preset-env: `DEBUG` option` amended at top of the bundle?

Here all the details:

```
 ∴  videomail-client (develop) : ./node_modules/.bin/browserify test/**/*.test.js -d -t [ babelify ] | node
[stdin]:1
babel-preset-env: `DEBUG` option
                ^

SyntaxError: Unexpected token :
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:569:30)
    at evalScript (bootstrap_node.js:432:27)
    at Socket.<anonymous> (bootstrap_node.js:198:15)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
```

to reproduce, git clone https://github.com/binarykitchen/videomail-client, npm install and do npm test (just change piped output to node)

**Comment by hzoo** [comment]
? when you use the debug mode it gets printed to STDOUT so maybe there's an issue with your setup?

**Comment by binarykitchen** [comment]
@hzoo yeah, true. piped that to `node` instead, fixed some errors and now am stuck here

```
└─( 2 ) ❱❱❱ browserify test/**/*.test.js -d -t [ babelify ] | node                           1 ⏎  +2761 22:48 ❰─┘
[stdin]:15906
  , html = doc.documentElement;
              ^

TypeError: Cannot read property 'documentElement' of undefined
    at Object.378../readystate ([stdin]:15906:15)
    at s ([stdin]:1:254)
    at [stdin]:1:305
    at Object.413../constants ([stdin]:21773:19)
    at s ([stdin]:1:254)
    at [stdin]:1:305
    at Object.443../../../src/client ([stdin]:28544:15)
    at s ([stdin]:1:254)
    at e ([stdin]:1:425)
    at [stdin]:1:443
```

`doc` is undefined? Hmmm, what to do here?
