### ISSUE TITLE
I tried babel-preset-env 2.0.0-beta.1 and module build failed

### ISSUE THREAD

**Issue by poi-mashiro** [babel/babel-preset-env#425]
I read an article about babel-preset-env 2.0.0-beta.1. And I tried it in my **_vue-cli_** demo. I updated it from 1.3.2 to 2.0.0-beta.1.
package.json
<pre><code>"dependencies": {
    "babel-polyfill": "^6.26.0",
    "vue": "^2.3.3",
    "vue-router": "^2.6.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^2.0.0-beta.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",</code></pre>

.babelrc
<pre><code>{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      },
      "useBuiltIns": "usage"
    }],
    "stage-2"
  ],
  // "plugins": ["transform-runtime"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}</code></pre>  

Then I typed "npm run dev" and saw this error:  

error  in ./src/components/date.vue  

Module build failed: TypeError: ../src/components/date.vue: path.arrowFunctionToExpression is not a function
    at PluginPass.ArrowFunctionExpression (..\node_modules\babel-plugin-transform-es2015-arrow-functions\lib\index.js:10:14)
    at newFn (..\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (..\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (..\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (..\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (..\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (..\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (..\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (..\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (..\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (..\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (..\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (..\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (..\node_modules\babel-core\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (..\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (..\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:150:16)  

<pre><code> @ ./src/components/date.vue 8:2-101
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/view/datepick.vue
 @ ./src/view/datepick.vue
 @ ./src/router/routes.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js  </code></pre>

I don't know how to fix it

**Comment by poi-mashiro** [comment]
I ensured that my vue-cli demo was ok for "npm run dev", before I tried **_babel-preset-env 2.0.0-beta.1_**.

**Comment by loganfsmyth** [comment]
The beta version of 2.0 is meant to work with the beta version of Babel 7.x. It will not work when used on Babel 6.x.

**Comment by poi-mashiro** [comment]
Thanks. I updated all babel to 7.0 beta.1 and succeeded. Its new characteristics "**'useBuiltIns': 'usage'**" is really exciting
