### ISSUE TITLE
env@2: `debug: true` fails with Invalid Version: false.0.0

### ISSUE THREAD

**Issue by tleunen** [babel/babel-preset-env#439]
When enabling `debug`, I'm getting this error:
```
babel-preset-env: `DEBUG` option

Using targets:
TypeError: [BABEL] /xxx/src/providers/message.js: Invalid Version: false.0.0 (While processing: "/xxx/node_modules/babel-preset-env/lib/index.js")
    at new SemVer (/xxx/node_modules/semver/semver.js:293:11)
    at Function.major (/xxx/node_modules/semver/semver.js:551:10)
    at prettifyVersion (/xxx/node_modules/babel-preset-env/lib/utils.js:33:33)
    at /xxx/node_modules/babel-preset-env/lib/utils.js:55:15
    at Array.reduce (<anonymous>)
    at prettifyTargets (/xxx/node_modules/babel-preset-env/lib/utils.js:51:31)
    at buildPreset (/xxx/node_modules/babel-preset-env/lib/index.js:226:59)
    at loadDescriptor (/xxx/node_modules/babel-core/lib/config/option-manager.js:252:14)
    at loadPresetDescriptor (/xxx/node_modules/babel-core/lib/config/option-manager.js:334:14)
    at /xxx/node_modules/babel-core/lib/config/option-manager.js:76:14
```

Here's my config:
```
    presets: [
        [
            'env',
            {
                targets: {
                    forceAllTransforms: false,
                    ignoreBrowserslistConfig: true,
                    node: 'current',
                },
                modules: 'commonjs',
                loose: true,
                useBuiltIns: 'usage',
                debug: true,
                exclude: ['transform-regenerator', 'transform-async-to-generator'],
            },
        ],
        'react',
    ],
```

**Comment by existentialism** [comment]
@tleunen thanks for the report.

We can certainly provide a better error message here, but you have two options inside of `targets` that are invalid (`forceAllTransforms`, `ignoreBrowserslistConfig`).

**Comment by tleunen** [comment]
Oh, I see. Actually, my real config is a bit different (with variables).. What should I assign the property to not use it at all ?

When using `undefined`, I'm getting this error:
```
Cannot read property 'toString' of undefined
```

**Comment by existentialism** [comment]
Meaning you don't want to declare targets? You can simply omit it, and it won't attempt to do any target-related filtering.

**Comment by tleunen** [comment]
Yep! Sorry, I misread at first ;)
Everything looks good now :)

**Comment by existentialism** [comment]
@tleunen awesome! glad it's working!
