### ISSUE TITLE
Strange behavior when setting targets = { chrome: 55 }.

### ISSUE THREAD

**Issue by AJIh** [babel/babel-preset-env#66]
Thanks for your preset. It makes babel transformation much more graceful. :)

I encountered a strange problem when setting targets = { chrome: 55 }. 

```
ERROR in ./src/client.js
    Module parse failed: ./react-starter-kit/node_modules/babel-loader/lib/index.js?{"cacheDirectory":true,"babelrc":false,"presets":[["env",{"targets":{"chrome":55},"useBuiltIns":true,"debug":true}],"react"],"plugins":["react-hot-loader/babel","transform-object-rest-spread","transform-class-properties","transform-runtime","transform-react-jsx-source","transform-react-jsx-self"]}!/Users/ajih/Documents/git/react-starter-kit/src/client.js Unexpected token (156:6)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (156:6)
```

It seems that async functions is not recognized by babel. Setting `chrome=54` or adding `transform-async-to-generators` to whitelist will solve the problem(but will transform async functions to generators).

I have created a [repo](https://github.com/AJIh/react-starter-kit) based on react-starter-kit to reproduce the bug.

The webpack and babel config is in file [tools/webpack.config.js](https://github.com/AJIh/react-starter-kit/blob/bug-babel-preset-env/tools/webpack.config.js#L42).

**Comment by hzoo** [comment]
Thanks!

I can check out the repo later but could you post the console/stack trace from the error? It should print out the plugins being used as well as the actual code snippet that is failing?

**Comment by AJIh** [comment]
The full stack trace(client and server bundles are built simultaneously):

```
[01:55:44] Starting 'start'...
[01:55:44] Starting 'clean'...
[01:55:45] Finished 'clean' after 203 ms
[01:55:45] Starting 'copy'...
[01:55:45] Finished 'copy' after 144 ms
webpack built 05f22db8f622da49ff5d in 2860ms
Child
    Time: 2860ms

    ERROR in ./src/client.js
    Module parse failed: /Users/ajih/Documents/git/react-starter-kit/node_modules/babel-loader/lib/index.js?{"cacheDirectory":true,"babelrc":false,"presets":["react",["env",{"targets":{"chrome":55},"useBuiltIns":true,"debug":true}]],"plugins":["react-hot-loader/babel","transform-object-rest-spread","transform-class-properties","transform-runtime","transform-react-jsx-source","transform-react-jsx-self"]}!/Users/ajih/Documents/git/react-starter-kit/src/client.js Unexpected token (156:6)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (156:6)
        at Parser.pp$4.raise (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:2221:15)
        at Parser.pp.unexpected (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:603:10)
        at Parser.pp.semicolon (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:581:61)
        at Parser.pp$1.parseExpressionStatement (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:966:10)
        at Parser.pp$1.parseStatement (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:730:24)
        at Parser.pp$1.parseTopLevel (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:638:25)
        at Parser.parse (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:516:17)
        at Object.parse (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:3098:39)
        at Parser.parse (/Users/ajih/Documents/git/react-starter-kit/node_modules/webpack/lib/Parser.js:902:15)
        at NormalModule.<anonymous> (/Users/ajih/Documents/git/react-starter-kit/node_modules/webpack/lib/NormalModule.js:104:16)
     @ multi client
Child
    Time: 3349ms
                                           Asset     Size  Chunks             Chunk Names
       components/Header/logo-small.png?2f751285  2.83 kB          [emitted]
    components/Header/logo-small@2x.png?8844262b  6.81 kB          [emitted]
                                 ../../server.js   236 kB       0  [emitted]  server
                             ../../server.js.map   210 kB       0  [emitted]  server
webpack: bundle is now VALID.
Error: Cannot find module './assets'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ajih/Documents/git/react-starter-kit/build/webpack:/external "./assets":1:1)
    at __webpack_require__ (/Users/ajih/Documents/git/react-starter-kit/build/webpack:/webpack/bootstrap 8f820d8ee9d775335e76:19:1)
    at Object.<anonymous> (/Users/ajih/Documents/git/react-starter-kit/build/webpack:/src/server.js:30:1)
    at __webpack_require__ (/Users/ajih/Documents/git/react-starter-kit/build/webpack:/webpack/bootstrap 8f820d8ee9d775335e76:19:1)
    at /Users/ajih/Documents/git/react-starter-kit/build/webpack:/webpack/bootstrap 8f820d8ee9d775335e76:39:1
    at Object.<anonymous> (/Users/ajih/Documents/git/react-starter-kit/build/server.js:45:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
/Users/ajih/Documents/git/react-starter-kit/tools/runServer.js:76
          throw new Error(`Server terminated unexpectedly with code: ${ code } signal: ${ signal }`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (/Users/ajih/Documents/git/react-starter-kit/tools/runServer.js:54:17)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `babel-node tools/run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'babel-node tools/run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
```

**Comment by hzoo** [comment]
So looking at this the error is acorn via webpack

 SyntaxError: Unexpected token (156:6)
        at Parser.pp$4.raise (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:2221:15)
...
            at Parser.parse (/Users/ajih/Documents/git/react-starter-kit/node_modules/webpack/lib/Parser.js:902:15)

So need to figure out what the output code is or if it's just not able to transform some kind of code correctly.

If you could reduce the code in `client.js` we could figure out exactly what part of the code is causing the error

**Comment by AJIh** [comment]
webpack keeps throwing an error even if `client.js` is reduced to these three lines.😂

```javascript
async function hello() {
  return 42;
}
```

The stack trace:

```
[02:31:07] Starting 'start'...
[02:31:07] Starting 'clean'...
[02:31:07] Finished 'clean' after 226 ms
[02:31:07] Starting 'copy'...
[02:31:07] Finished 'copy' after 154 ms
babel-preset-env: `DEBUG` option

Using targets: {
  "chrome": 55
}

modules transform: commonjs

Using plugins:

 syntax-trailing-function-commas {}

Using polyfills:

 es7.string.pad-start {}

 es7.string.pad-end {}
webpack built 05f22db8f622da49ff5d in 1709ms
webpack building...
webpack built 05f22db8f622da49ff5d in 33ms
Child
    Time: 33ms

    ERROR in ./src/client.js
    Module parse failed: /Users/ajih/Documents/git/react-starter-kit/node_modules/babel-loader/lib/index.js?{"cacheDirectory":true,"babelrc":false,"presets":["react",["env",{"targets":{"chrome":55},"useBuiltIns":true,"debug":true}]],"plugins":["react-hot-loader/babel","transform-object-rest-spread","transform-class-properties","transform-runtime","transform-react-jsx-source","transform-react-jsx-self"]}!/Users/ajih/Documents/git/react-starter-kit/src/client.js Unexpected token (3:6)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (3:6)
        at Parser.pp$4.raise (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:2221:15)
        at Parser.pp.unexpected (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:603:10)
        at Parser.pp.semicolon (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:581:61)
        at Parser.pp$1.parseExpressionStatement (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:966:10)
        at Parser.pp$1.parseStatement (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:730:24)
        at Parser.pp$1.parseTopLevel (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:638:25)
        at Parser.parse (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:516:17)
        at Object.parse (/Users/ajih/Documents/git/react-starter-kit/node_modules/acorn/dist/acorn.js:3098:39)
        at Parser.parse (/Users/ajih/Documents/git/react-starter-kit/node_modules/webpack/lib/Parser.js:902:15)
        at NormalModule.<anonymous> (/Users/ajih/Documents/git/react-starter-kit/node_modules/webpack/lib/NormalModule.js:104:16)
     @ multi client
```

**Comment by hzoo** [comment]
so weird. I think the version of webpack/acorn might be outdated so it errors? I don't know if it's only webpack 2 that supports that or not but it might be the case. At this point it's not a Babel issue because the problem is that webpack doesn't understand async

**Comment by AJIh** [comment]
webpack 1 is using acorn 3.0([package.json](https://github.com/webpack/webpack/blob/webpack-1/package.json#L7)). acorn starts supporting async from version [4.0.0](https://github.com/ternjs/acorn/releases/tag/4.0.0).

In acorn doc
> Support for `async`/`await` syntax when `ecmaVersion` is >= 8.

webpack 2 is using acorn 4.0 and specifying [`ecmaVersion: 2017`](https://github.com/webpack/webpack/blob/c07847dbd40967a5599ad7133600d5b5122b02e2/lib/Parser.js#L1123).

I think using webpack 2 is the right way to solve the problem. Thanks for explanation. :)

**Comment by hzoo** [comment]
Cool, thanks for trying it out!

**Comment by huangyingjie** [comment]
I have the same issue: Browserify cannot understand async.

target source code:
````js
const test = async () => {};
module.exports = test;
````
SyntaxError: Unexpected token (5:22) while parsing file: xxxx

acorn verison:
````js
├─┬ browserify@14.3.0
│ ├─┬ insert-module-globals@7.0.1
│ │ └─┬ lexical-scope@1.2.0
│ │   └─┬ astw@2.2.0
│ │     └── acorn@4.0.11
````
package.json
````js
      [
        "babelify",
        {
          "presets": [
            [
              "env",
              {
                "targets": {
                  "browsers": [
                    "chrome >= 55"
                  ]
                }
              }
            ]
          ]
        }
      ],
````
